version: '3'
services:
  mongo:
    security_opt:
      - label:disable
    image: mongo:6
    container_name: thequest-mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - .podman-data/mongo:/data/db
    ports:
      - 27021:27017
